"""
Django settings for lms_backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['mendoura-web.onrender.com', 'mendoura.com', 'www.mendoura.com', 'localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = [
    'https://mendoura.com',
    'https://www.mendoura.com',
    'https://mendoura-web.onrender.com',
]

# Render terminates SSL for us and forwards this header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 week, raise once confirmed stable
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    'cloudinary_storage',
    'cloudinary',

    # تأكدي إن السطر ده مكتوب كدة بالظبط برة وجنب القائمة
    'courses',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lms_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'courses.context_processors.tracks_menu',
                'courses.context_processors.pending_instructor_requests',
                'courses.context_processors.pending_course_approvals',
                'courses.context_processors.pending_track_requests',
            ],
        },
    },
]

WSGI_APPLICATION = 'lms_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL')
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# English and Arabic ship with real, reviewed translations. Do not add more
# LANGUAGES entries with machine-translated .po files -- that's how you end
# up publishing bad translations under the brand's name. Adding a new
# language later is just a new locale/<code>/LC_MESSAGES/django.po plus an
# entry here, no code changes.
LANGUAGES = [
    ('en', 'English'),
    ('ar', 'العربية'),
    ('fr', 'Français'),
    ('es', 'Español'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']


AUTH_USER_MODEL = 'courses.User'


# Django's own default (/accounts/login/) has no URL route in this project
# (the real login page is /login/, see courses/urls.py) -- without this,
# every @login_required view (including @admin_required, e.g. the Admin
# Panel, Send Test Email, and Accept/Reject links) redirects a signed-out
# or session-expired visitor to a URL that 404s instead of to the login
# form.
LOGIN_URL = 'login'

# Where to redirect users after a successful login
LOGIN_REDIRECT_URL = 'platform_home'

# Where to redirect users after logging out
LOGOUT_REDIRECT_URL = 'platform_home'

# Media files (User uploaded content like thumbnails)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary Configuration (persistent file storage for uploads)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default=''),
}

STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    # Non-manifest storage: still gzip/brotli-compresses static files, but
    # doesn't require every file to have an exact, pre-computed hashed-name
    # manifest entry. The Manifest variant raises a hard 500 (ValueError:
    # Missing staticfiles manifest entry) for *any* request touching a
    # {% static %} tag whose entry didn't make it into staticfiles.json for
    # any reason -- we hit that in production and traded the cache-busting
    # benefit for not having every page depend on a perfectly synced manifest.
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}


# Increase upload limits for video/file uploads
DATA_UPLOAD_MAX_MEMORY_SIZE = 209715200  # 200MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 209715200  # 200MB

# Paymob (Egypt-compatible payment processor -- Stripe does not support payouts
# to Egypt-based accounts). Get these from the Paymob merchant dashboard.
PAYMOB_API_KEY = config('PAYMOB_API_KEY', default='')
PAYMOB_INTEGRATION_ID_CARD = config('PAYMOB_INTEGRATION_ID_CARD', default='', cast=str)
PAYMOB_IFRAME_ID = config('PAYMOB_IFRAME_ID', default='')
PAYMOB_HMAC_SECRET = config('PAYMOB_HMAC_SECRET', default='')

# Bunny Stream (video hosting/CDN). Videos upload directly from the
# instructor's browser to Bunny via a short-lived signed upload -- the API
# key never leaves the server. Playback uses token-signed embed URLs so a
# leaked link expires and can't be reshared.
#   BUNNY_API_KEY    -- the Stream library's API key (creates videos, signs uploads)
#   BUNNY_TOKEN_KEY  -- the Stream library's Token Authentication Key (signs
#                       embed URLs); leave blank to fall back to referrer-only
#                       security until it's provided.
BUNNY_LIBRARY_ID = config('BUNNY_LIBRARY_ID', default='')
BUNNY_API_KEY = config('BUNNY_API_KEY', default='')
BUNNY_TOKEN_KEY = config('BUNNY_TOKEN_KEY', default='')
# How long a signed embed URL stays valid (seconds). Long enough to watch a
# lecture without the token expiring mid-video.
BUNNY_EMBED_TOKEN_TTL = 60 * 60 * 6  # 6 hours

# Outgoing email (password reset, certificates, etc.) via Zoho Mail SMTP,
# sent from a dedicated no-reply@mendoura.com mailbox -- support@mendoura.com
# stays the human-monitored contact address linked in email footers, never
# the sender. Falls back to the console backend -- prints the email instead
# of sending it -- whenever EMAIL_HOST_PASSWORD isn't set, so local dev/tests
# never try (and fail) a real SMTP connection.
#
# Zoho's two valid combinations are port 587 with EMAIL_USE_TLS=True
# (STARTTLS, the default below) or port 465 with EMAIL_USE_SSL=True --
# mixing them (e.g. port 465 with only EMAIL_USE_TLS set) fails the
# connection. EMAIL_USE_SSL is exposed here so switching to port 465 is a
# pure env-var change if that's ever needed, instead of a code edit.
# EMAIL_HOST must match the Zoho account's actual data center --
# smtp.zoho.com for the default/global region, smtp.zoho.eu / smtp.zoho.in
# / etc. for others; this project's MX records (mx.zoho.com/mx2/mx3) show
# it's on the default .com region, so the default below matches.
EMAIL_HOST = config('EMAIL_HOST', default='smtp.zoho.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='no-reply@mendoura.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Mendoura <no-reply@mendoura.com>')
# Without this, smtplib's socket has no timeout at all -- if Zoho's SMTP
# server (or the network path to it) is ever slow or unreachable, the
# connection attempt blocks *forever*. No amount of try/except in emails.py
# helps against that: the request just hangs until the WSGI worker's own
# timeout kills it, which is what a raw, un-graceful 500 (rather than
# Django's own error handling) looks like from the browser. This turns that
# indefinite hang into a normal, catchable socket.timeout well before any
# gunicorn worker timeout would fire.
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)
EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST_PASSWORD
    else 'django.core.mail.backends.console.EmailBackend'
)

# How long a password reset link stays valid, in seconds. Explicit here
# (rather than relying on Django's own 3-day default) so it's one source of
# truth: courses/urls.py derives the "expires in X" wording in the reset
# email from this same value instead of a second hardcoded copy of the number.
PASSWORD_RESET_TIMEOUT = config('PASSWORD_RESET_TIMEOUT', default=60 * 60 * 24 * 3, cast=int)  # 3 days

# Where the "new Instructor application" internal notification goes -- kept
# separate from support@mendoura.com's use as the human reply-to contact
# address elsewhere, in case this ever needs to route to a dedicated
# admissions inbox instead.
INSTRUCTOR_APPLICATION_NOTIFICATION_EMAIL = config(
    'INSTRUCTOR_APPLICATION_NOTIFICATION_EMAIL', default='support@mendoura.com')

# AI Study Buddy -- Anthropic Claude API key. Blank in local dev/tests is
# fine; the view surfaces a friendly error instead of crashing when it's unset.
AI_API_KEY = config('AI_API_KEY', default='')

# Auto-translation of Track/Course/legal content (courses/auto_translate.py)
# uses deep-translator's free GoogleTranslator -- no key or billing needed,
# on by default. Unrelated to AI_API_KEY above (that's only the separate AI
# Study Buddy feature). Defaults to off under `manage.py test` so the
# hundreds of tests that incidentally save a Track/Course/legal record as
# test fixture setup don't all make real network calls -- the handful of
# tests that specifically exercise translation opt back in with
# @override_settings(AUTO_TRANSLATE_ENABLED=True).
AUTO_TRANSLATE_ENABLED = config(
    'AUTO_TRANSLATE_ENABLED', default=('test' not in sys.argv), cast=bool)

# Without this, Django's default logging config sends 500 errors to
# mail_admins (which does nothing since ADMINS isn't set) and prints nothing
# to the console -- so a production 500 leaves no trace anywhere. This makes
# every unhandled exception print its full traceback to stderr, which Render
# captures in the service's Logs tab.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'timestamped': {
            'format': '%(asctime)s %(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'timestamped',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Without this, courses.* loggers (auto_translate, emails, ...)
        # have no configured handler and fall through to Python's silent
        # "last resort" behavior -- only WARNING+ reaches stderr, with no
        # formatting, and INFO-level calls (like the [TRANSLATION_DEBUG]
        # success-path logging) are dropped entirely, never reaching
        # Render's logs at all.
        'courses': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
