# Generated by Django 5.2.16 on 2026-07-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_user_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="payoneer_account",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Payoneer email or account ID. Required for instructors based outside Egypt.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="revenue_share_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tax_clause_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
