# Generated by Django 5.2.16 on 2026-07-23 16:41

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_user_country_user_payoneer_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=200)),
                ("intro", models.TextField(blank=True, default="")),
                ("last_updated", models.DateField()),
                ("title_translations", models.JSONField(blank=True, default=dict)),
                ("intro_translations", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["slug"],
            },
            bases=(courses.models.AutoTranslatedFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LegalSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("anchor", models.SlugField(blank=True, max_length=100)),
                ("heading", models.CharField(max_length=255)),
                (
                    "body",
                    models.TextField(
                        help_text="Markdown -- supports tables, bold, and lists."
                    ),
                ),
                ("heading_translations", models.JSONField(blank=True, default=dict)),
                ("body_translations", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="courses.legaldocument",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
            bases=(courses.models.AutoTranslatedFieldsMixin, models.Model),
        ),
    ]
