# Generated by Django 5.2.16 on 2026-07-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_legaldocument_legalsection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="revenue_share_accepted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tax_clause_accepted_at",
        ),
    ]
