# Generated by Django 5.2.16 on 2026-08-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_question_alter_course_ai_script_choice_quiz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="poster_image",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to="course_posters/"
            ),
        ),
    ]
