# Generated by Django 5.2.16 on 2026-08-01 22:51

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0023_course_poster_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits, spaces and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[courses.models.SpacesAllowedUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
