# Generated by Django 5.2.16 on 2026-08-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0026_trackrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="transcript_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="lecture",
            name="transcript_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
