# Generated by Django 5.2.16 on 2026-08-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0027_lecture_transcript_error_lecture_transcript_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackrequest",
            name="new_category_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="trackrequest",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"parent__isnull": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="track_requests",
                to="courses.track",
            ),
        ),
        migrations.AddConstraint(
            model_name="trackrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("parent__isnull", False), ("new_category_name", "")),
                    models.Q(
                        ("parent__isnull", True),
                        models.Q(("new_category_name", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="trackrequest_exactly_one_of_parent_or_new_category",
            ),
        ),
    ]
