# Generated by Django 5.2.16 on 2026-08-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_choice_text_translations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="ai_generated_script_translations",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
